### ISSUE TITLE
How to quit presentation

### ISSUE THREAD

**Issue by blubbsy** [neuralyzer/dokuwiki-plugin-revealjs#10]
Hi,

how do you exit the presentation when you reached the end of it? I cant figure it out and have to edit the url to leave it again.

Blubbsy.

**Comment by ogobrecht** [comment]
Hi,

I had the same problem - the s5 plugin goes direct back to the wiki page - no matter on which slide we are. Revealjs updates the browser history, so a back click in the browser goes back to the previous slide and NOT back to the previous wiki page.

To workaround this you can open the slides always in a new browser tab. But for this you have to modify the plugin. Have a look in `<yourWikiRoot>/lib/plugins/revealjs/syntax/theme.php` around line 67 and put the attribute `target="_blank"` inside the link:

~~~php
$renderer->doc .= '<a  target="_blank" href="...
~~~

@neuralyzer: This should be an option like in the DokuWiki core - what do you mean?

![image](https://cloud.githubusercontent.com/assets/10425445/18269910/af24a74e-742a-11e6-813f-6a7536ea9327.png)

**Comment by neuralyzer** [comment]
Hi,

it's true, at the moment there is no easy way to leave the presentation. I think opening the presentation in a new tab as ogobrecht suggested is an option which is easily implemented. I guess alternatively it could be something like pressing the Esc key?

**Comment by ogobrecht** [comment]
Hmmm,

Esc key is not so nice for mobile devices. Also, this is used by some browsers to stop the fullscreen mode - at least in Chrome? Or I am wrong (have currently no access to a desktop computer to verify it...)

And is there a shortcut in Revealjs for the Esc key? Sorry, can this also not verify in the moment.

On mobile devices the tab handling should be ok.

Best regards
Ottmar

**Comment by neuralyzer** [comment]
Very convincing point about the mobile devices. I'll add an option for the link target as you suggested.

**Comment by ogobrecht** [comment]
Hi,

thank you for your fast response time and for the great plugin :-)

I have some other suggestions - I just started to using your plugin and collecting ideas at the moment. This is also the reason, why I was answering this question - by browsing your project for old and current issues. I will come back to you the next days, if it is ok for you.

Best regards
Ottmar

**Comment by neuralyzer** [comment]
Hi,
I very much appreciate any idea and feedback. Looking forward!

Cheers

**Comment by neuralyzer** [comment]
I added an option to open presentations in a new  window or tab. I also made this behavior the new default. So I'm closing the issue with commit b106d66ab26089b6b9891739133c34626808400f .

**Comment by ogobrecht** [comment]
Thank you :-)
