### ISSUE TITLE
Feature Request: Presenter's Notes

### ISSUE THREAD

**Issue by anthonyclarka2** [neuralyzer/dokuwiki-plugin-revealjs#15]
I am sorry if this is already implemented, but I didn't see any reference to it in the demo dokuwiki page.

It would be nice if we could add hidden text to each "slide" h2 or h3 section that shows up as presenters notes.

**Comment by geraldolsribeiro** [comment]
Some speaker notes syntax will be provided in the future? Any workaround?

**Comment by neuralyzer** [comment]
Hi there,
I'm wondering about a syntax for that. Something like a <note></note> tag?

**Comment by neuralyzer** [comment]
Closed with ogobrecht's commit 0f61937dbf1e9b227bff7156337b31142bda63d1. Ogobrecht implemented presenter notes.
