### ISSUE TITLE
Feature: Make presentation available via link or shortcut

### ISSUE THREAD

**Issue by j0hannes** [neuralyzer/dokuwiki-plugin-revealjs#4]
... like that ugly icon in the S5 plugin.

**Comment by bug** [comment]
+1
and adding a header section to the page or a ~~revealjs~~ line to specify options such as theme or background image would be nice too.

**Comment by neuralyzer** [comment]
I see. I'll have a look into this on the weekend. I guess I will just add something very similar to the S5 plugin theme handling option.

**Comment by neuralyzer** [comment]
Feature added via (https://github.com/neuralyzer/dokuwiki-plugin-revealjs/commit/065b6110d19e7d5c0ec180844c76e0b3bbb6984e).
