### ISSUE TITLE
Add theme selection option on a per page basis

### ISSUE THREAD

**Issue by j0hannes** [neuralyzer/dokuwiki-plugin-revealjs#6]
&theme=... doesn't have any effect anymore; the default theme is always chosen.

**Comment by neuralyzer** [comment]
Yes. That is right. This option was removed in reveal.js 3.0. See [this link](https://github.com/hakimel/reveal.js/issues/1061) and also [here](https://github.com/hakimel/reveal.js/releases).

**Comment by neuralyzer** [comment]
I should add: The plugin comes with a config option which allows to set the theme globally for the whole wiki. For the moment it is not possible to set the theme on a per presentation basis.

**Comment by j0hannes** [comment]
I would really appreciate the option to choose between different layouts for different presentations.

When thinking about the option to have a "presentation link" at the respective wiki pages (like what the S5 plugin does), a great feature would be a dropdown box to choose the theme having the preconfigured one (wiki-wise unless specified for that page) selected.

**Comment by neuralyzer** [comment]
Feature added via (https://github.com/neuralyzer/dokuwiki-plugin-revealjs/commit/065b6110d19e7d5c0ec180844c76e0b3bbb6984e).

**Comment by j0hannes** [comment]
Many thanks!
