### ISSUE TITLE
How do you override the default transition?

### ISSUE THREAD

**Issue by FFAxKenny** [neuralyzer/dokuwiki-plugin-revealjs#8]
Might be a silly question, but how do you change the transition on the page? There's a way to include a theme in the current syntax, but is there a way to do it for transitions?

**Comment by neuralyzer** [comment]
Hi,

at the moment this cannot be done. Are you talking about an overall transition setting for a whole presentation or a per slide setting?

**Comment by FFAxKenny** [comment]
Overall transition settings for a whole presentation.

**Comment by neuralyzer** [comment]
You can change the transition in your wiki's configuration manager as admin. This changes the transition for all presentations in the whole wiki.

**Comment by neuralyzer** [comment]
I'm closing this issue assuming that the overall transition setting for the whole wiki is good enough. Let me know if  a transition setting for a single presentation is required or open a new issue specifically for transition settings for single  presentations.

**Comment by ogobrecht** [comment]
Hi,

I have created a general solution, which is able to handle all current and future options without changing the code again.

I created a pull request for this. Please have a look and let me know, if I should change something or if you don't like this at all.

Sorry, I am new to the pull/merge things. If I do something wrong, let me also know.

Best regards
Ottmar
