### ISSUE TITLE
minor change I had to do in rendered.php

### ISSUE THREAD

**Issue by itsho** [neuralyzer/dokuwiki-plugin-revealjs#9]
Hi.

in the following file

> dokuwiki\lib\plugins\revealjs\renderer.php

I had to change 
`function listitem_open($level) {`

to 
`function listitem_open($level, $node = false) {`

to fix compatibility error with `Doku_Renderer_xhtml`:

> Warning: Declaration of renderer_plugin_revealjs::listitem_open(level)shouldbecompatiblewithDokuRendererxhtml::listitemopen(level, $node = false) in ...\dokuwiki\lib\plugins\revealjs\renderer.php on line 16

**Comment by neuralyzer** [comment]
Thanks for pointing that out. 

Closed with commit 2aabd0e9379a7037940c787a8665c16681afa095

**Comment by itsho** [comment]
my pleasure.  thank you for this wonderful plugin.
